DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
    /*ID*/
    ID bigserial UNIQUE NOT NULL,
    /*客戶名稱*/
    NAME varchar(255) NOT NULL,
    /*信箱*/
    EMAIL text UNIQUE DEFAULT NULL,
    /*生日*/
    BIRTHDAY date DEFAULT NULL,
    /*點數*/
    POINT int NOT NULL,
    /*建立時間*/
    CREATED_AT timestamp DEFAULT current_timestamp,
    /*修改時間*/
    UPDATED_AT timestamp DEFAULT NULL,
    /*建立者*/
    CREATED_BY varchar(255) DEFAULT 'system',
    /*修改者*/
    UPDATED_BY varchar(255) DEFAULT NULL,
    /*版本*/
    VERSION bigint DEFAULT 0,
    PRIMARY KEY (ID)
); 

COMMENT ON TABLE CUSTOMER IS '客戶資訊';
COMMENT ON COLUMN CUSTOMER.ID IS 'ID';
COMMENT ON COLUMN CUSTOMER.NAME IS '客戶名稱';
COMMENT ON COLUMN CUSTOMER.EMAIL IS '信箱';
COMMENT ON COLUMN CUSTOMER.BIRTHDAY IS '生日';
COMMENT ON COLUMN CUSTOMER.POINT IS '點數';
COMMENT ON COLUMN CUSTOMER.CREATED_AT IS '建立時間';
COMMENT ON COLUMN CUSTOMER.UPDATED_AT IS '修改時間';
COMMENT ON COLUMN CUSTOMER.CREATED_BY IS '建立者';
COMMENT ON COLUMN CUSTOMER.UPDATED_BY IS '修改者';
COMMENT ON COLUMN CUSTOMER.VERSION IS '版本';

